### ISSUE TITLE
mac下安装好了protoc后，编译voyager失败

### ISSUE THREAD

**Issue by freewings85** [QiumingLu/voyager#1]
/Documents/skywalk/skywalker/third_party/voyager/voyager/rpc/rpc_channel.cc:40:14: note: in instantiation of member function 'voyager::ProtobufCodec<voyager::RpcMessage>::SendMessage' requested
      here
  if (codec_.SendMessage(conn_, msg)) {
             ^
1 error generated.
make[2]: *** [voyager/rpc/CMakeFiles/voyager_rpc.dir/rpc_channel.cc.o] Error 1
make[1]: *** [voyager/rpc/CMakeFiles/voyager_rpc.dir/all] Error 2

**Comment by QiumingLu** [comment]
protobuf是编译安装的吗？还是brew安装的，建议按照我给的文档编译安装protobuf，而不仅仅是protoc

**Comment by freewings85** [comment]
嗯，按照你的步骤重新装了下protobuf，编译成功了，谢谢
